### ISSUE TITLE
Support Maven Central distribution

### ISSUE THREAD

**Issue by foo4u** [foo4u/spring-mvc-cache-control#15]
Get artifacts distributed via Maven Central.

**Comment by fdw** [comment]
Any updates on this? This project would be really helpful for me.

**Comment by foo4u** [comment]
Sorry for the delay. I was able to get an account Maven Central. However, signing the POM with Gradle's maven-publish is a real pain. Spent a few hours on it and got frustrated. I'll try to revisit next week.

**Comment by fdw** [comment]
Cool, thank you!

**Comment by jitpack** [comment]
One simple alternative is using https://jitpack.io

**Comment by foo4u** [comment]
Sorry for the delay. Still working through signing issues. Looking into two options:

1. Switching to JCenter (signed up, waiting for approval)
2. Reverting to the legacy maven plugin

@jitpack looks like a cool service but the website isn't clear on what "sends jars back to you means." Does the repository owner use your service or does the end user just use jitpack as a source repo?

**Comment by jitpack** [comment]
@foo4u The end user adds https://jitpack.io as a maven repository to their gradle build file. When they build their project gradle will ask jitpack.io for the jar and jitpack will build it. That is if it hasn't been built before.
For this project the settings would be: https://jitpack.io/#foo4u/spring-mvc-cache-control/1.0.0 .

**Comment by fdw** [comment]
Unfortunately, this is not an option for me: I'm working for a larger company, and I cannot modify the list of repositories we use. Therefore, it would be easiest if you could add it to Maven Central. JCenter may also be possible, but Jitpack is definitely out.

**Comment by foo4u** [comment]
We're finally in [Maven Central][0]. Will close after I update the readme!

[0]: http://search.maven.org/#search%7Cga%7C1%7CRossillo%20

**Comment by fdw** [comment]
This is great news! Thank you so much!

**Comment by foo4u** [comment]
Closing since complete for 1.1.0. However, 1.1.0-RELEASE on Central is compiled with Java 8. Will do a patch release compiled with Java 1.6.
