### ISSUE TITLE
Cannot open projects because "repoUser" is not set

### ISSUE THREAD

**Issue by fdw** [foo4u/spring-mvc-cache-control#20]
Hi,
I forked the repo and tried to open it in IntelliJ. However, I can't get it to work as IntelliJ complains about a property "repoUser" that is not set. Do you have any idea what I'm missing?

Thanks!

**Comment by foo4u** [comment]
Just edit your `~/.gradle/gradle.properties` file and add:

    repoUser=foo
    repoPass=bar

Sorry, tried to find the right balance between secure releases and easy development. Gradle makes shipping releases non-trivial. I believe 4.x simplifies things a bit.
